//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exebite.GoogleSheetAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exebite.GoogleSheetAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1G2jNerUrjX597V5gbjtDfSQfvICbkrqTEaVipFN1gTQ.
        /// </summary>
        internal static string HEY_DAY {
            get {
                return ResourceManager.GetString("HEY_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13D2HvRTAON6KZSGfGkKI6wJ_vwiJOVfUkPINl00gvGE.
        /// </summary>
        internal static string INDEX_HOUSE {
            get {
                return ResourceManager.GetString("INDEX_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1m7S2VQQn3q5vsx1WHEIRcQKF7HUPDDzqgBYvm8P2VQE.
        /// </summary>
        internal static string KASA {
            get {
                return ResourceManager.GetString("KASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12ubn-spYqoTQMc3uLGxxxx_bcHnt6ECmySmUbIUcG1E.
        /// </summary>
        internal static string LIPA {
            get {
                return ResourceManager.GetString("LIPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1xb0OFRg9n0HF-rIn7NcdfR2AzGnLYTqiuXbZdeY5ydc.
        /// </summary>
        internal static string MIMAS {
            get {
                return ResourceManager.GetString("MIMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1tr9B7Qmym6fqLS_tNFWnO8Tyl--u4vVAQwA6j00dNOc.
        /// </summary>
        internal static string PARRILLA {
            get {
                return ResourceManager.GetString("PARRILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credentials.json.
        /// </summary>
        internal static string SACredentialsLocation {
            get {
                return ResourceManager.GetString("SACredentialsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1y3CHHotB9lPif2-yaRffM3yTr9GhfwpGfvO4PJkFCZQ.
        /// </summary>
        internal static string SERPICA {
            get {
                return ResourceManager.GetString("SERPICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.serpica021.rs/funkcije/getJelaZaDan.php.
        /// </summary>
        internal static string SERPICA_DAILY_MENU_URL {
            get {
                return ResourceManager.GetString("SERPICA_DAILY_MENU_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.serpica021.rs/funkcije/logovanje.php.
        /// </summary>
        internal static string SERPICA_LOGIN_URL {
            get {
                return ResourceManager.GetString("SERPICA_LOGIN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        internal static string SERPICA_PASSWORD {
            get {
                return ResourceManager.GetString("SERPICA_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 060123456.
        /// </summary>
        internal static string SERPICA_USERNAME {
            get {
                return ResourceManager.GetString("SERPICA_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1la8e99oGeafMF6dqQhLzYhZ9-INO6C240Ox_RKDUlmo.
        /// </summary>
        internal static string TOPLI_OBROK {
            get {
                return ResourceManager.GetString("TOPLI_OBROK", resourceCulture);
            }
        }
    }
}
