//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exebite.GoogleSheetAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exebite.GoogleSheetAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1jEfZsZVmlPQf5aDozLiAmTbEcHXTi_M7-gXmHaJauys.
        /// </summary>
        internal static string DE_PAPAJ {
            get {
                return ResourceManager.GetString("DE_PAPAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1w5jCZQU0WVEj6o0RzBX5ALYWWoLcd8eRBvK6OebSJxs.
        /// </summary>
        internal static string HEDONE {
            get {
                return ResourceManager.GetString("HEDONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ehEqncAQP677e8Fi4oWTOBvLjEUB67ApjFLJnBO3gcY.
        /// </summary>
        internal static string INDEX_HOUSE {
            get {
                return ResourceManager.GetString("INDEX_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1p95HwHCwbx80L3aWXsStkGbmNfYgG5JOvRvONm0JUXI.
        /// </summary>
        internal static string KASA {
            get {
                return ResourceManager.GetString("KASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1FJt865bBn69jsbRpyVTqQAFarUjvsiKsom1c2JfR0Hk.
        /// </summary>
        internal static string LIPA {
            get {
                return ResourceManager.GetString("LIPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1YQ6BH2vOmGkxNgDWzct_j3Dznql0OWrwi1nITrtlZHA.
        /// </summary>
        internal static string MIMAS {
            get {
                return ResourceManager.GetString("MIMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credentials.json.
        /// </summary>
        internal static string SACredentialsLocation {
            get {
                return ResourceManager.GetString("SACredentialsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SERPICA {
            get {
                return ResourceManager.GetString("SERPICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Sp_9P9qSWd3ENkjhbs2slzBHPJNIg-QeuL0vG7L2gKA.
        /// </summary>
        internal static string TEGLAS {
            get {
                return ResourceManager.GetString("TEGLAS", resourceCulture);
            }
        }
    }
}
