//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exebite.GoogleSheetAPI.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exebite.GoogleSheetAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
<<<<<<< HEAD Looks up a localized string similar to 1kfebqHeFkcrO_Tj0stG9NDbFxb_4nM3K8U2uMQ66dtc.
        /// </summary>
        internal static string HEY_DAY {
            get {
        {
            get
            return ResourceManager.GetString("HEY_DAY", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to 13D2HvRTAON6KZSGfGkKI6wJ_vwiJOVfUkPINl00gvGE.
=======
        ///   Looks up a localized string similar to 1Eb3QSsvk3jHcULkl2gyM8_Y56ElaQLWVon6A37oy7Jc.
>>>>>>> dev    return ResourceManager.GetString("INDEX_HOUSE", resourceCulture);
            }
        }
        {
            get
           
        /// <summary>
        ///   Looks up a localized string similar to 1y-PZeeCjK4hGi6Z3i_C4UITfuRIsDEGIzo45V0evGZY.
        /

        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 1m7S2VQQn3q5vsx1WHEIRcQKF7HUPDDzqgBYvm8P2VQE.
=======
        ///   Looks up a localized string similar to 1J9Q5MbLg66aT22QCjjX7InlKK8b-OXeZHWXjmUenrrc.
>>>>>>> dev<summary>
        ///   Looks up a localized string similar to 1TiRdknQjMqB9tOdIKgxQ-8bkMC4c_dYrJXcUzC-QoyM.
        /// </summary>
        {
            get
           l static string LIPA {
            get {
                return ResourceManager.GetString("LIPA", resourceCulture);
         

        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 12ubn-spYqoTQMc3uLGxxxx_bcHnt6ECmySmUbIUcG1E.
=======
        ///   Looks up a localized string similar to 1GjiSV7n-wivAUaiGQl0SOjDkKMY29SvgFTLfzfPVHiQ.
>>>>>>> devget {
                return ResourceManager.GetString("MIMAS", resourceCulture);
            }
        {
            get
           
        
        /// <summary>
        /

        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 1xb0OFRg9n0HF-rIn7NcdfR2AzGnLYTqiuXbZdeY5ydc.
=======
        ///   Looks up a localized string similar to 1kaB79osJftUkw5s8RchsJrB2PUqcrOwyxS2PXFIlap0.
>>>>>>> dev
        /// <summary>
        ///   Looks up a localized s
        {
            get
           ummary>
        internal static string SACredentialsLocation {
            get {
         
   }
        }
        
        /// <summary>
        ///   Looks up a localized stri
        {
            get
           ummary>
        internal static string SERPICA {
            get {
         
   }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to
        {
            get
           ummary>
        internal static string SERPICA_DAILY_MENU_URL {
            get {
         
   }
        }
        
        /// <summary>
        ///   Looks up a localized str
        {
            get
           ummary>
        internal static string SERPICA_LOGIN_URL {
            get {
         

        /// <summary>
<<<<<<< HEAD
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        {
            get
           l static string SERPICA_PASSWORD {
            get {
                return ResourceManager.GetString("SERPICA_PASSWORD", resourceCulture);
         

        
        /// <summary>
        ///   Looks up a localized string similar to 060123456.
        /// </summary>
        {
            get
           l static string SERPICA_USERNAME {
            get {
                return ResourceManager.GetString("SERPICA_USERNAME", resourceCulture);
         

        
        /// <summary>
        ///   Looks up a localized string similar to 1ILH3zHu47nMjOvqbF2nRpq-lJjaAciCCIXt7far3xk4.
        /// </summary>
        {
            get
           l static string TOPLI_OBROK {
            get {
                return ResourceManager.GetString("TOPLI_OBROK", resourceCulture);
         

    }
}
