//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleSpreadsheetApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\nberdic\\source\\repos\\FoodOrdering\\GoogleSpreadSheetApi\\Resources\\client_" +
            "secret.json")]
        public string json_location {
            get {
                return ((string)(this["json_location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E1U6l1Xh1vO1MHw3FR2RfQT-iQTDzNKJ69WpBp5UYko")]
        public string HedoneSpredsheetID {
            get {
                return ((string)(this["HedoneSpredsheetID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1RD-lkAiM2W3Jkh4isoVIXEVLv1zgReHo4imSELAFVHc")]
        public string ExtraFoodSpredsheetID {
            get {
                return ((string)(this["ExtraFoodSpredsheetID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1QGYPsCq_5u84FUtL89xGmeedNA753KtqBqox_CG3QQE")]
        public string IndexHauseSpredsheetID {
            get {
                return ((string)(this["IndexHauseSpredsheetID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1Qvb_hosYZBTt50d8B_FTx1Uvxuo06OQI-f1k0d858VM")]
        public string LipaSpredsheetID {
            get {
                return ((string)(this["LipaSpredsheetID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1jOUHYfi0b6i4BTjBvmOQYGvBqC0MKv0-g7oSU07BUUU")]
        public string TeglasSpredsheetID {
            get {
                return ((string)(this["TeglasSpredsheetID"]));
            }
        }
    }
}
